[broker]
address = "kafka:29092"
topic = "ccx.ocp.results"
group = "aggregator"
enabled = true

[server]
address = ":8080"
api_prefix = "/api/insights-results-aggregator/v1/"
api_spec_file = "openapi.json"
debug = true

[processing]
org_whitelist = "org_whitelist.csv"

[storage]
db_driver = "postgres"
pg_username = "user"
pg_password = "password"
pg_host = "localhost"
pg_port = 55432
pg_db_name = "aggregator"
pg_params = "sslmode=disable"
log_sql_queries = true
